//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Taller_Moto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Almacen_Repuesto_MotosEntities : DbContext
    {
        public Almacen_Repuesto_MotosEntities()
            : base("name=Almacen_Repuesto_MotosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barrio> Barrios { get; set; }
        public virtual DbSet<Cargo> Cargoes { get; set; }
        public virtual DbSet<Ciudad> Ciudads { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<DetalleFacturaVenta> DetalleFacturaVentas { get; set; }
        public virtual DbSet<DetallePedidoProveedor> DetallePedidoProveedors { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<EmpleadoCargo> EmpleadoCargoes { get; set; }
        public virtual DbSet<FacturaCompra> FacturaCompras { get; set; }
        public virtual DbSet<FacturaServicio> FacturaServicios { get; set; }
        public virtual DbSet<FacturaVenta> FacturaVentas { get; set; }
        public virtual DbSet<Garantia> Garantias { get; set; }
        public virtual DbSet<ImagenesProducto> ImagenesProductoes { get; set; }
        public virtual DbSet<Pai> Pais { get; set; }
        public virtual DbSet<PedidoProveedor> PedidoProveedors { get; set; }
        public virtual DbSet<Perfil> Perfils { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<Repuesto> Repuestoes { get; set; }
        public virtual DbSet<Sede> Sedes { get; set; }
        public virtual DbSet<Servicio> Servicios { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TelefonoCliente> TelefonoClientes { get; set; }
        public virtual DbSet<TipoTelefono> TipoTelefonoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<UsuarioPerfil> UsuarioPerfils { get; set; }
    }
}
