//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Taller_Moto.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedidoProveedor
    {
        public int IdDetalle { get; set; }
        public Nullable<int> IdPedido { get; set; }
        public Nullable<int> IdRepuesto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        [JsonIgnore]

        public virtual PedidoProveedor PedidoProveedor { get; set; }
        [JsonIgnore]
        public virtual Repuesto Repuesto { get; set; }
    }
}
