//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Taller_Moto.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedidoProveedor
    {
        public int IdDetalle { get; set; }
        public Nullable<int> IdPedido { get; set; }
        public Nullable<int> IdRepuesto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        [JsonIgnore]

        public virtual PedidoProveedor PedidoProveedor { get; set; }
        [JsonIgnore]
        public virtual Repuesto Repuesto { get; set; }
    }
}
