//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Taller_Moto.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoCargo
    {
        public int IdCodigo { get; set; }
        public Nullable<int> Documento { get; set; }
        public Nullable<int> CodigoSede { get; set; }
        public Nullable<int> CodigoCargo { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFIn { get; set; }
        [JsonIgnore]

        public virtual Cargo Cargo { get; set; }
        [JsonIgnore]
        public virtual Empleado Empleado { get; set; }
        [JsonIgnore]
        public virtual Sede Sede { get; set; }
    }
}
