//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Taller_Moto.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoCargo
    {
        public int IdCodigo { get; set; }
        public Nullable<int> Documento { get; set; }
        public Nullable<int> CodigoSede { get; set; }
        public Nullable<int> CodigoCargo { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFIn { get; set; }
        [JsonIgnore]

        public virtual Cargo Cargo { get; set; }
        [JsonIgnore]
        public virtual Empleado Empleado { get; set; }
        [JsonIgnore]
        public virtual Sede Sede { get; set; }
    }
}
