//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Taller_Moto.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaServicio
    {
        public int IdFacturaServicio { get; set; }
        public Nullable<int> IdFacturaVenta { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public string Descripcion { get; set; }
        [JsonIgnore]

        public virtual FacturaVenta FacturaVenta { get; set; }
        [JsonIgnore]
        public virtual Servicio Servicio { get; set; }
    }
}
