//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Taller_Moto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaCompra
    {
        public int IdFacturaCompra { get; set; }
        public Nullable<int> IdPedido { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
    
        public virtual PedidoProveedor PedidoProveedor { get; set; }
    }
}
