//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Taller_Moto.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaCompra
    {
        public int IdFacturaCompra { get; set; }
        public Nullable<int> IdPedido { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        [JsonIgnore]

        public virtual PedidoProveedor PedidoProveedor { get; set; }
    }
}
