//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Taller_Moto.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaServicio
    {
        public int IdFacturaServicio { get; set; }
        public Nullable<int> IdFacturaVenta { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public string Descripcion { get; set; }
        [JsonIgnore]

        public virtual FacturaVenta FacturaVenta { get; set; }
        [JsonIgnore]
        public virtual Servicio Servicio { get; set; }
    }
}
