//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Taller_Moto.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoProveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoProveedor()
        {
            this.DetallePedidoProveedors = new HashSet<DetallePedidoProveedor>();
            this.FacturaCompras = new HashSet<FacturaCompra>();
        }
    
        public int IdPedido { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdSede { get; set; }
        public string Estado { get; set; }
        [JsonIgnore]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedidoProveedor> DetallePedidoProveedors { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaCompra> FacturaCompras { get; set; }
        [JsonIgnore]
        public virtual Proveedor Proveedor { get; set; }
        [JsonIgnore]
        public virtual Sede Sede { get; set; }
    }
}
