//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Taller_Moto.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioPerfil
    {
        public int CodigoUs { get; set; }
        public Nullable<int> CodigoUsuario { get; set; }
        public Nullable<int> CodigoPerfil { get; set; }
        public bool Activo { get; set; }
        [JsonIgnore]

        public virtual Perfil Perfil { get; set; }
        [JsonIgnore]
        public virtual Usuario Usuario { get; set; }
    }
}
